### ISSUE TITLE
AsyncCommand updates CanExecute somewhat late and/or not at all

### ISSUE THREAD

**Issue by cmeeren** [StephenCleary/Mvvm.Async#13]
Not sure why this is happening, but I can't figure it out.

My command is defined like this:

```c#
public AsyncCommand ToggleCheckedCommand { get; }

// constructor
public MyViewModel()
{
    ToggleCheckedCommand = new AsyncCommand(ToggleCheckedAsync);
}

private async Task ToggleCheckedAsync(object _)
{
    var response = await ServerApi.DoWebRequestAsync();
    if (response.Success)
        ...
}
```

If I debug the app and break at `await ServerApi.DoWebRequestAsync()`, and mouseover ToggleCheckedCommand, `Execution` is null and `IsExecuting` is False. If I perform the web request and continue to the next line, `if (response.Success)`, Execution and IsExecuting assume the expected values.

If I unit test my viewmodel and mock `ServerApi`, so that it returns instantly,  `Execution` is null and `IsExecuting` is False throughout the test (as seen when debugging and breaking at the same lines). This makes the test fail, since I'm checking for whether or not the command is disabled during execution.

Is this something you can reproduce? Using v1.0.0-eta-02.

**Comment by StephenCleary** [comment]
This was happening because the command was starting the delegate before it updated its properties. So, if you were to check the properties from *within* the command (before the first `await`), you would see the old values. The UI layer would never see them, since they would be updated by the time `ICommand.Execute` returned.

`1.0.0-eta-03` changes this behavior by delaying the delegate execution until the properties have been updated. [This unit test](https://github.com/StephenCleary/Mvvm.Async/blob/496648c2f24f5752508412586460bb536306c864/test/UnitTests/AsyncCommandUnitTests.cs#L48) will catch regressions.
