### ISSUE TITLE
PropertyChangedEventArgsCache

### ISSUE THREAD

**Issue by jmo-gelsight** [StephenCleary/Mvvm.Async#37]
This isn't really an "issue" more like a question.  I did not see a category for general discussion so I am posting it here.  I hope that is ok.

I notice you use the `PropertyChangedEventArgsCache`, when raising `PropertyChanged` event.    I've come across this lazy-caching-the-args approach elsewhere in implementations of `INotifyPropertyChanged`.  My understanding is that this is to avoid slamming the garbage collector with too many allocations when the property changes really fly.  Is my understanding correct?

Because using this also means that you must lock the the global cache lock every single time you want to raise a`PropertyChanged` for any client that uses it. Is that really better?   Has anyone ever done any performance testing on this?

If you know your class might raise many `PropertyChanged ` events in a short enough time span to have an effect on performance, then why not simply have static, readonly instances of `PropertyChangedEventArgs` for those properties inside their owning classes?

**Comment by StephenCleary** [comment]
> My understanding is that this is to avoid slamming the garbage collector with too many allocations when the property changes really fly. Is my understanding correct?

Sort of. "Cache" is a misnomer because the items never *leave* the cache. So it's just a way of "allocate this thing only once".

> Because using this also means that you must lock the the global cache lock every single time you want to raise aPropertyChanged for any client that uses it. Is that really better? Has anyone ever done any performance testing on this?

The locking is usually trivial; the vast majority of the time, the UI thread is the only one using the cache, and taking an uncontested lock is extremely fast (every `lock` starts with a spinlock).

> If you know your class might raise many PropertyChanged  events in a short enough time span to have an effect on performance, then why not simply have static, readonly instances of PropertyChangedEventArgs for those properties inside their owning classes?

The intended usage for this kind of cache helper is in a `ViewModelBase` kind of type that implements `INotifyPropertyChanged` for properties of its derived classes. This kind of base type is very common in data binding apps once they reach a certain size. A base type like that would need to handle any property name (i.e., a `string` name) instead of having static properties (or worse, making its derived types define the static properties).

**Comment by jmo-gelsight** [comment]
Yes, that's how I've seen it used before.  I inherited a ViewModelBase class that did something similar actually but I long ago removed it and just cached the values raised most frequently.  Perhaps I should restore it.  Thank you for the answer!
