### ISSUE TITLE
Can't capture AsyncCommand exception

### ISSUE THREAD

**Issue by gpbicego** [StephenCleary/Mvvm.Async#6]
Hi Stephen,
I'm trying to use AsyncCommand, this is my example code:

```
        public AsyncCommand TestCommand
        {
            get
            {
                if (_testCommand == null)
                {
                    _testCommand = new AsyncCommand(
                        async (x) =>
                        {
                            await SaveAsync();
                        });
                }
                return _testCommand;
            }
        }
        private async Task SaveAsync()
        {
            await Task.Delay(1);
            throw new NotImplementedException();
        }
```

The exception in SaveAsync isn't captured by AsyncCommand.
What is wrong with my code?

Thank you
Giampaolo

**Comment by gpbicego** [comment]
I solved in this way:
`public override async Task ExecuteAsync(object parameter)
{
	//Execution = NotifyTask.Create(_executeAsync(parameter));
	Execution = NotifyTask.Create( new Task(()=>_executeAsync(parameter)));
        ...`
Is this right?

**Comment by gpbicego** [comment]
Waiting for your reply, I temporarily solved this way:
```
public override async Task ExecuteAsync(object parameter)
{
	//Execution = NotifyTask.Create(_executeAsync(parameter));
	Execution = NotifyTask.Create( new Task(()=>_executeAsync(parameter)));
```

**Comment by StephenCleary** [comment]
An older version of my `AsyncCommand` did capture exceptions; however, this version does not. This is by design. Other implementations of `ICommand` do not capture exceptions, so this change brings `IAsyncCommand`/`AsyncCommand` more in line with mainstream MVVM.

The best way to think about `AsyncCommand` is like an asynchronous event handler. The behavior of throwing from `AsyncCommand` should be (roughly) the same as throwing from an async event handler.
